Globalize.addCultureInfo("pt", {
    messages: {
        Yes: "Sim",
        No: "Não",
        Cancel: "Cancelar",
        Clear: "Limpar",
        Done: "Concluído",
        Loading: "A carregar...",
        Select: "Seleccionar...",
        Search: "Pesquisar...",
        Back: "Voltar",
        OK: "Confirmar",
        "dxCollectionWidget-noDataText": "Sem dados",
        "validation-required": "Preenchimento obrigatório",
        "validation-required-formatted": "{0} é de preenchimento obrigatório",
        "validation-numeric": "O valor deve um número",
        "validation-numeric-formatted": "{0} deve um número",
        "validation-range": "O valor está fora do intervalo",
        "validation-range-formatted": "{0} está fora do intervalo",
        "validation-stringLength": "O comprimento do valor não é correcto",
        "validation-stringLength-formatted": "O comprimento de {0} não é correcto",
        "validation-custom": "Valor inválido",
        "validation-custom-formatted": "{0} é inválido",
        "validation-compare": "Os valores não coincidem",
        "validation-compare-formatted": "{0} não coincide",
        "validation-pattern": "O valor não coincide com o padrão",
        "validation-pattern-formatted": "{0} não coincide com o padrão",
        "validation-email": "O Email é inválido",
        "validation-email-formatted": "{0} é inválido",
        "validation-mask": "Valor inválido"
    }
});
Globalize.addCultureInfo("pt", {
    messages: {
        "dxLookup-searchPlaceholder": "Número mínimo de caracteres: {0}",
        "dxList-pullingDownText": "Pressionar para recarregar...",
        "dxList-pulledDownText": "Soltar para recarregar...",
        "dxList-refreshingText": "A recarregar...",
        "dxList-pageLoadingText": "A carregar...",
        "dxList-nextButtonText": "Mais",
        "dxList-selectAll": "Seleccionar Tudo",
        "dxListEditDecorator-delete": "Eliminar",
        "dxListEditDecorator-more": "Mais",
        "dxScrollView-pullingDownText": "Pressionar para recarregar...",
        "dxScrollView-pulledDownText": "Soltar para recarregar...",
        "dxScrollView-refreshingText": "A recarregar...",
        "dxScrollView-reachBottomText": "A carregar...",
        "dxDateBox-simulatedDataPickerTitleTime": "Seleccionar hora",
        "dxDateBox-simulatedDataPickerTitleDate": "Seleccionar data",
        "dxDateBox-simulatedDataPickerTitleDateTime": "Seleccionar data e hora",
        "dxDateBox-validation-datetime": "O valor deve ser uma data ou uma hora",
        "dxFileUploader-selectFile": "Seleccione um ficheiro",
        "dxFileUploader-dropFile": "ou Solte um ficheiro aqui",
        "dxFileUploader-bytes": "Bytes",
        "dxFileUploader-kb": "kb",
        "dxFileUploader-Mb": "Mb",
        "dxFileUploader-Gb": "Gb",
        "dxFileUploader-upload": "Carregar",
        "dxFileUploader-uploaded": "Carregado",
        "dxFileUploader-readyToUpload": "Pronto para carregar",
        "dxFileUploader-uploadFailedMessage": "O carregamento falhou",
        "dxRangeSlider-ariaFrom": "Desde {0}",
        "dxRangeSlider-ariaTill": "Até {0}",
        "dxSwitch-onText": "Ligado",
        "dxSwitch-offText": "Desligado"
    }
});

Globalize.addCultureInfo("pt", {
    messages: {
        "dxDataGrid-columnChooserTitle": "Selector de coluna",
        "dxDataGrid-columnChooserEmptyText": "Soltar uma coluna aqui para a esconder",
        "dxDataGrid-groupContinuesMessage": "Continua na página seguinte",
        "dxDataGrid-groupContinuedMessage": "Continuação da página anterior",
        "dxDataGrid-editingEditRow": "Editar",
        "dxDataGrid-editingSaveRowChanges": "Guardar",
        "dxDataGrid-editingCancelRowChanges": "Cancelar",
        "dxDataGrid-editingDeleteRow": "Eliminar",
        "dxDataGrid-editingUndeleteRow": "Restaurar",
        "dxDataGrid-editingConfirmDeleteMessage": "Tem a certeza que pretende eliminar este registo?",
        "dxDataGrid-editingConfirmDeleteTitle": "",
        "dxDataGrid-groupPanelEmptyText": "Soltar aqui um cabeçalho de coluna para agrupar por essa coluna",
        "dxDataGrid-noDataText": "Sem dados",
        "dxDataGrid-searchPanelPlaceholder": "Pesquisar...",
        "dxDataGrid-filterRowShowAllText": "(Todos)",
        "dxDataGrid-filterRowResetOperationText": "Repor",
        "dxDataGrid-filterRowOperationEquals": "Igual",
        "dxDataGrid-filterRowOperationNotEquals": "Diferente",
        "dxDataGrid-filterRowOperationLess": "Menor que",
        "dxDataGrid-filterRowOperationLessOrEquals": "Menor que ou igual a",
        "dxDataGrid-filterRowOperationGreater": "Maior que",
        "dxDataGrid-filterRowOperationGreaterOrEquals": "Maior que ou igual a",
        "dxDataGrid-filterRowOperationStartsWith": "Começa com",
        "dxDataGrid-filterRowOperationContains": "Contém",
        "dxDataGrid-filterRowOperationNotContains": "Não contém",
        "dxDataGrid-filterRowOperationBetween": "Entre",
        "dxDataGrid-filterRowOperationEndsWith": "Termina com",
        "dxDataGrid-applyFilterText": "Aplicar filtro",
        "dxDataGrid-trueText": "verdadeiro",
        "dxDataGrid-falseText": "falso",
        "dxDataGrid-sortingAscendingText": "Ordem ascendente",
        "dxDataGrid-sortingDescendingText": "Ordem descendente",
        "dxDataGrid-sortingClearText": "Eliminar ordenação",
        "dxDataGrid-editingSaveAllChanges": "Guardar alterações",
        "dxDataGrid-editingCancelAllChanges": "Descartar alterações",
        "dxDataGrid-editingAddRow": "Adicionar linha",
        "dxDataGrid-summaryMin": "Mín: {0}",
        "dxDataGrid-summaryMinOtherColumn": "Mínimo de {1} é {0}",
        "dxDataGrid-summaryMax": "Máx: {0}",
        "dxDataGrid-summaryMaxOtherColumn": "Máximo de {1} é {0}",
        "dxDataGrid-summaryAvg": "Média: {0}",
        "dxDataGrid-summaryAvgOtherColumn": "Média de {1} é {0}",
        "dxDataGrid-summarySum": "Soma: {0}",
        "dxDataGrid-summarySumOtherColumn": "Soma de {1} é {0}",
        "dxDataGrid-summaryCount": "Contagem: {0}",
        "dxDataGrid-columnFixingFix": "Corrigir",
        "dxDataGrid-columnFixingUnfix": "Eliminar correcção",
        "dxDataGrid-columnFixingLeftPosition": "Para a esquerda",
        "dxDataGrid-columnFixingRightPosition": "Para a direita",
        "dxDataGrid-exportTo": "Exportar para",
        "dxDataGrid-exportToExcel": "Exportar para ficheiro Excel",
        "dxDataGrid-excelFormat": "Ficheiro Excel",
        "dxDataGrid-selectedRows": "Linhas seleccionadas",
        "dxDataGrid-headerFilterEmptyValue": "(Vazio)",
        "dxDataGrid-headerFilterOK": "Confirmar",
        "dxDataGrid-headerFilterCancel": "Cancelar",
        "dxDataGrid-ariaColumn": "Coluna",
        "dxDataGrid-ariaValue": "Valor",
        "dxDataGrid-ariaFilterCell": "Filtro de célula",
        "dxDataGrid-ariaCollapse": "Recolher",
        "dxDataGrid-ariaExpand": "Expandir",
        "dxDataGrid-ariaDataGrid": "Grelha de dados",
        "dxDataGrid-ariaSearchInGrid": "Procurar na grelha de dados",
        "dxDataGrid-ariaSelectAll": "Seleccionar tudo",
        "dxDataGrid-ariaSelectRow": "Seleccionar linha",
        "dxPager-infoText": "Página {0} de {1}",
        "dxPivotGrid-grandTotal": "Total geral",
        "dxPivotGrid-total": "{0} Total",
        "dxPivotGrid-fieldChooserTitle": "Selector de Campos",
        "dxPivotGrid-showFieldChooser": "Mostrar Selector de Campos",
        "dxPivotGrid-expandAll": "Expandir todos",
        "dxPivotGrid-collapseAll": "Recolher todos",
        "dxPivotGrid-sortColumnBySummary": "Ordenar \"{0}\" por esta coluna",
        "dxPivotGrid-sortRowBySummary": "Ordenar \"{0}\" por esta linha",
        "dxPivotGrid-removeAllSorting": "Eliminar todas as ordenações",
        "dxPivotGrid-rowFields": "Campos de Linha",
        "dxPivotGrid-columnFields": "Campos de Coluna",
        "dxPivotGrid-dataFields": "Campos de Dados",
        "dxPivotGrid-filterFields": "Campos do Filtro",
        "dxPivotGrid-allFields": "Todos os Campos",
        "dxScheduler-editorLabelTitle": "Assunto",
        "dxScheduler-editorLabelStartDate": "Data de início",
        "dxScheduler-editorLabelEndDate": "Data de término",
        "dxScheduler-editorLabelDescription": "Descrição",
        "dxScheduler-editorLabelRecurrence": "Repetir",
        "dxScheduler-openAppointment": "Abrir compromisso",
        "dxScheduler-recurrenceNever": "Nunca",
        "dxScheduler-recurrenceDaily": "Diariamente",
        "dxScheduler-recurrenceWeekly": "Semanalmente",
        "dxScheduler-recurrenceMonthly": "Mensalmente",
        "dxScheduler-recurrenceYearly": "Anualmente",
        "dxScheduler-recurrenceEvery": "Todos os",
        "dxScheduler-recurrenceEnd": "Terminar repetição",
        "dxScheduler-recurrenceAfter": "Após",
        "dxScheduler-recurrenceOn": "Ligado",
        "dxScheduler-recurrenceRepeatDaily": "dia(s)",
        "dxScheduler-recurrenceRepeatWeekly": "semana(s)",
        "dxScheduler-recurrenceRepeatMonthly": "mês(es)",
        "dxScheduler-recurrenceRepeatYearly": "ano(s)",
        "dxScheduler-switcherDay": "Dia",
        "dxScheduler-switcherWeek": "Semana",
        "dxScheduler-switcherWorkWeek": "Semana de trabalho",
        "dxScheduler-switcherMonth": "Mês",
        "dxScheduler-recurrenceRepeatOnDate": "na data",
        "dxScheduler-recurrenceRepeatCount": "ocurrência(s)",
        "dxScheduler-allDay": "Todo o dia",
        "dxCalendar-todayButtonText": "Hoje",
        "dxCalendar-ariaWidgetName": "Calendário",
        "dxColorView-ariaRed": "Vermelho",
        "dxColorView-ariaGreen": "Verde",
        "dxColorView-ariaBlue": "Azul",
        "dxColorView-ariaAlpha": "Transparência",
        "dxColorView-ariaHex": "Codigo de Cor"
    }
});
